name: Lint Commits

on: [push]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: lint-commit-${{ github.event.pull_request.title }}
  cancel-in-progress: true

jobs:
  lint-commits:
    name: ⚙️ Lint Commits
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}
      - name: commitlint
        uses: wagoid/commitlint-github-action@v6
